1. 파이토치(PyTorch)

2017년 공개된 파이토치(PyTorch)는 넘파이(NumPy) 라이브러리처럼 연산을 위해 사용된다. toch, torch.autograd, torch.multiprocessing, toch.optim, torch.utils, torch.onnx로 구성된다.

설치 및 버전확인

In [1]:
import torch
torch.__version__

'2.5.0+cpu'

가. 텐서(Tensors)  
텐서는 데이터 표현을 위한 기본 구조로, 정6면체의 컨테이너로 묘사된다. 넘파이(numpy)의 ndarray와 유사하며 gpu를 사용한 연산가속이 가능하다.

초기화 되지 않은 텐서

In [2]:
x = torch.empty(4, 2)
print(x)

tensor([[2.4242e-27, 1.1883e-42],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00]])


무작위로 초기화된 텐서

In [3]:
x = torch.rand(4,2)  #rand는 radom의 약자. 랜덤하게 초기화됨
print(x)

tensor([[0.3593, 0.0073],
        [0.1527, 0.2560],
        [0.5075, 0.4945],
        [0.7586, 0.5808]])


데이터 타입(dtype)이 long이고, 0으로 채워진 텐서

In [5]:
x=torch.zeros(4,2, dtype=torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


사용자 입력 값으로 텐서 초기화

In [6]:
x=torch.tensor([3, 2.3])
print(x)

tensor([3.0000, 2.3000])


2x4크기, doble타입, 1로 채워진 텐서

In [7]:
x=x.new_ones(2,4,dtype=torch.double)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


x와 같은 크기, float 타입, 무작위로 채워진 텐서

In [9]:
x=torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 0.1123,  1.8655, -0.3437,  0.2660],
        [-1.2945, -0.4918,  0.5565, -0.5962]])


텐서의 크기 계산

In [10]:
print(x.size())

torch.Size([2, 4])


나. 데이터 타입(Data Type)

Data l type	l dtype	l CPU tensor l GPU tensor  
32-bit floating point l	torch.float32 or torch.float l	torch.FloatTensor l	torch.cuda.FloatTensor  
64-bit floating point l	torch.float64 or torch.double l	torch.DoubleTensor l torch.cuda.DoubleTensor  
16-bit floating point l	torch.float16 or torch.half	l torch.HalfTensor l torch.cuda.HalfTensor  
8-bit integer(unsinged) l torch.uint8 l torch.ByteTensor l torch.cuda.ByteTensor  
8-bit integer(singed) l	torch.int8 l torch.CharTensor l	torch.cuda.CharTensor  
16-bit integer(signed) l torch.int16 or torch.short l torch.ShortTensor l torch.cuda.ShortTensor  
32-bit integer(signed) l torch.int32 or torch.int l torch.IntTensor	l torch.cuda.IntTensor  
64-bit integer(signed) l torch.int64 or torch.long l torch.LongTensor l torch.cuda.LongTensor 

In [14]:
ft = torch.FloatTensor([1,2,3])
print(ft)  # 숫자뒤에 .이 붙은 것을 확인
print(ft.dtype)  # floattensor은 기본 32bit

tensor([1., 2., 3.])
torch.float32


In [16]:
print(ft.short())
print(ft.int())
print(ft.long()) # 캐스팅하여 long은 64bit에 해당함을 확인

tensor([1, 2, 3], dtype=torch.int16)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3])


In [20]:
it=torch.IntTensor([1,2,3])
print(it)
print(it.dtype)

tensor([1, 2, 3], dtype=torch.int32)
torch.int32


In [21]:
print(it.float())
print(it.double())
print(it.half())

tensor([1., 2., 3.])
tensor([1., 2., 3.], dtype=torch.float64)
tensor([1., 2., 3.], dtype=torch.float16)


CUDA Tensors
.to 메소드를 사용해 텐서를 어떠한 장치(cpu, gpu)로도 옮길 수 있음

In [22]:
x=torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([1.3890])
1.3890422582626343
torch.float32
